### ISSUE TITLE
Is there any way to take a random input?

### ISSUE THREAD

**Issue by DonCyriac** [arminbiere/aiger#3]

**Comment by arminbiere** [comment]
$ ./aigsim -h
usage: aigsim [<option> ...] [ <model> [<stimulus>] ]

with

<model>         AIG in AIGER format
<stimulus>      stimulus (file of 0/1/x input vectors)

and <option> one of the following

-h              usage
-m              copy/move outputs as bad properties
-c              check witness and do not print trace (implies '-w', '-2')
-w              assume stimulus is a witness (first line is '1')
-v              produce VCD output trace instead of transitions
-d              add delays between input and output changes to VCD
-f              force smart line filtering
-2              ground three valued stimulus by setting 'x' to '0'
-3              enable three valued stimulus in random simulation
-r <vectors>    random stimulus of <vectors> input vectors
-s <seed>       set seed of random number generator (default '0')
